version: '3.8'
volumes:
  data:
  data-bkp:
services:
  springbootapp:
    image: lerndevops/samples:springboot-app
    deploy:
      replicas: 4
#      placement:
#        constraints:
#          - node.labels.role==app
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 150M
    ports:
      - "9090:8080"
    depends_on:
      - mongo
  mongo:
    image: lerndevops/samples:mongodb
    deploy:
      replicas: 1
#      placement:
#        constraints:
#          - node.labels.role==db
      restart_policy:
        condition: on-failure
    ports: 
      - "27017:27017"
    volumes:
      - data:/data/db
      - data-bkp:/data/bkp
